-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  favorite_tools TEXT[],
  updated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON profiles FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own profile."
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile."
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- 2. TEMPLATES TABLE (n8n Templates)
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  workflow_json JSONB,
  tags TEXT[],
  category TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Templates
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Templates are viewable by everyone."
  ON templates FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert templates."
  ON templates FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own templates."
  ON templates FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own templates."
  ON templates FOR DELETE
  USING (auth.uid() = user_id);

-- 3. TEMPLATE COMMENTS TABLE
CREATE TABLE IF NOT EXISTS template_comments (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  template_id BIGINT REFERENCES templates(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Template Comments
ALTER TABLE template_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Template comments are viewable by everyone."
  ON template_comments FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert comments."
  ON template_comments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own comments."
  ON template_comments FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own comments."
  ON template_comments FOR DELETE
  USING (auth.uid() = user_id);

-- 4. BLOG POSTS TABLE
CREATE TABLE IF NOT EXISTS posts (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT,
  summary TEXT,
  content TEXT, -- HTML content
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Optional link to user
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Blog Posts
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Blog posts are viewable by everyone."
  ON posts FOR SELECT
  USING (true);

-- Only admins or specific users should be able to insert/update/delete blog posts.
-- For now, we'll allow authenticated users to insert (if that's the intended model), 
-- or restrict it. Given the API uses a master key or user token, let's assume 
-- authenticated users can create posts for now, or we can restrict it to a specific role.
-- Assuming a simple model where any auth user can create a post (community blog) or just admins.
-- Let's allow authenticated users to manage their own posts.

CREATE POLICY "Authenticated users can insert posts."
  ON posts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own posts."
  ON posts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own posts."
  ON posts FOR DELETE
  USING (auth.uid() = user_id);


-- 5. FORUM TOPICS TABLE
CREATE TABLE IF NOT EXISTS forum_topics (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Forum Topics
ALTER TABLE forum_topics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Forum topics are viewable by everyone."
  ON forum_topics FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert topics."
  ON forum_topics FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own topics."
  ON forum_topics FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own topics."
  ON forum_topics FOR DELETE
  USING (auth.uid() = user_id);


-- 6. FORUM COMMENTS TABLE
CREATE TABLE IF NOT EXISTS forum_comments (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  topic_id UUID REFERENCES forum_topics(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Forum Comments
ALTER TABLE forum_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Forum comments are viewable by everyone."
  ON forum_comments FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert forum comments."
  ON forum_comments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own forum comments."
  ON forum_comments FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own forum comments."
  ON forum_comments FOR DELETE
  USING (auth.uid() = user_id);

-- 7. FORUM EDITS TABLE
CREATE TABLE IF NOT EXISTS forum_edits (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  topic_id UUID REFERENCES forum_topics(id) ON DELETE CASCADE,
  comment_id UUID REFERENCES forum_comments(id) ON DELETE CASCADE,
  previous_title TEXT,
  previous_content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Forum Edits
ALTER TABLE forum_edits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Forum edits are viewable by everyone."
  ON forum_edits FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert forum edits."
  ON forum_edits FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 8. FORUM ATTACHMENTS TABLE
CREATE TABLE IF NOT EXISTS forum_attachments (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  topic_id UUID REFERENCES forum_topics(id) ON DELETE CASCADE,
  comment_id UUID REFERENCES forum_comments(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  mime_type TEXT,
  size_bytes BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Forum Attachments
ALTER TABLE forum_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Forum attachments are viewable by everyone."
  ON forum_attachments FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert forum attachments."
  ON forum_attachments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own forum attachments."
  ON forum_attachments FOR DELETE
  USING (auth.uid() = user_id);


-- 9. STORAGE BUCKET CONFIGURATION
-- Create 'avatars' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Create 'forum_attachments' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('forum_attachments', 'forum_attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow public access to avatars
CREATE POLICY "Avatar images are publicly accessible."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'avatars' );

-- Policy to allow authenticated users to upload avatars
CREATE POLICY "Authenticated users can upload avatars."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

-- Policy to allow users to update their own avatars
CREATE POLICY "Users can update their own avatars."
  ON storage.objects FOR UPDATE
  USING ( bucket_id = 'avatars' AND auth.uid() = owner )
  WITH CHECK ( bucket_id = 'avatars' AND auth.uid() = owner );

-- Policy to allow users to delete their own avatars
CREATE POLICY "Users can delete their own avatars."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'avatars' AND auth.uid() = owner );

-- Policy to allow public access to forum attachments
CREATE POLICY "Forum attachments are publicly accessible."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'forum_attachments' );

-- Policy to allow authenticated users to upload forum attachments
CREATE POLICY "Authenticated users can upload forum attachments."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'forum_attachments' AND auth.role() = 'authenticated' );

-- Policy to allow users to delete their own forum attachments
CREATE POLICY "Users can delete their own forum attachments."
  ON storage.objects FOR DELETE
  USING ( bucket_id = 'forum_attachments' AND auth.uid() = owner );


