import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { ToolsIndexComponent } from './components/tools/tools-index/tools-index.component';
import { CronGeneratorComponent } from './components/tools/cron-generator/cron-generator.component';
import { JsonFormatterComponent } from './components/tools/json-formatter/json-formatter.component';
import { PlaceholderComponent } from './components/shared/placeholder/placeholder.component';
import { UrlCodecComponent } from './components/tools/url-codec/url-codec.component';
import { Base64CodecComponent } from './components/tools/base64-codec/base64-codec.component';
import { JwtDecoderComponent } from './components/tools/jwt-decoder/jwt-decoder.component';
import { TimestampConverterComponent } from './components/tools/timestamp-converter/timestamp-converter.component';
import { N8nExpressionSimulatorComponent } from './components/tools/n8n-expression-simulator/n8n-expression-simulator.component';
import { DataConverterComponent } from './components/tools/data-converter/data-converter.component';
import { HashGeneratorComponent } from './components/tools/hash-generator/hash-generator.component';
import { PasswordGeneratorComponent } from './components/tools/password-generator/password-generator.component';
import { UuidGeneratorComponent } from './components/tools/uuid-generator/uuid-generator.component';
import { RegexTesterComponent } from './components/tools/regex-tester/regex-tester.component';
import { MockDataGeneratorComponent } from './components/tools/mock-data-generator/mock-data-generator.component';
import { WebhookTesterComponent } from './components/tools/webhook-tester/webhook-tester.component';
import { MyIpComponent } from './components/tools/my-ip/my-ip.component';
import { RestClientComponent } from './components/tools/rest-client/rest-client.component';
import { DnsCheckerComponent } from './components/tools/dns-checker/dns-checker.component';
import { SslCheckerComponent } from './components/tools/ssl-checker/ssl-checker.component';
import { DiffCheckerComponent } from './components/tools/diff-checker/diff-checker.component';
import { DockerComposeGeneratorComponent } from './components/tools/docker-compose-generator/docker-compose-generator.component';
import { QrCodeGeneratorComponent } from './components/tools/qr-code-generator/qr-code-generator.component';
import { BlogListComponent } from './components/blog/blog-list/blog-list.component';
import { BlogPostComponent } from './components/blog/blog-post/blog-post.component';
import { LoginComponent } from './components/login/login.component';
import { ProfileComponent } from './components/profile/profile.component';
import { N8nManagerComponent } from './components/tools/n8n-manager/n8n-manager.component';
import { ForumListComponent } from './components/forum/forum-list/forum-list.component';
import { ForumNewTopicComponent } from './components/forum/forum-new-topic/forum-new-topic.component';
import { ForumTopicComponent } from './components/forum/forum-topic/forum-topic.component';
import { TemplateListComponent } from './components/templates/template-list/template-list.component';
import { TemplateDetailComponent } from './components/templates/template-detail/template-detail.component';
import { BoxShadowGeneratorComponent } from './components/tools/box-shadow-generator/box-shadow-generator.component';
import { CssGradientGeneratorComponent } from './components/tools/css-gradient-generator/css-gradient-generator.component';
import { ClipPathGeneratorComponent } from './components/tools/clip-path-generator/clip-path-generator.component';
import { CssGridBuilderComponent } from './components/tools/css-grid-builder/css-grid-builder.component';
import { CssFilterGeneratorComponent } from './components/tools/css-filter-generator/css-filter-generator.component';
import { CssAnimationGeneratorComponent } from './components/tools/css-animation-generator/css-animation-generator.component';
import { LearningIndexComponent } from './components/learning/learning-index/learning-index.component';
import { LearningPathComponent } from './components/learning/learning-path/learning-path.component';

export const APP_ROUTES: Routes = [
  { path: 'login', component: LoginComponent },
  { path: 'profile', component: ProfileComponent },
  { path: '', component: HomeComponent },
  { path: 'blog', component: BlogListComponent },
  { path: 'blog/:slug', component: BlogPostComponent },
  { path: 'forum', component: ForumListComponent },
  { path: 'forum/new', component: ForumNewTopicComponent },
  { path: 'forum/:topicId', component: ForumTopicComponent },
  { path: 'templates', component: TemplateListComponent },
  { path: 'templates/:id', component: TemplateDetailComponent },
  { path: 'learning', component: LearningIndexComponent },
  { path: 'learning/:slug', component: LearningPathComponent },
  { path: 'tools', component: ToolsIndexComponent },
  { path: 'tools/gerador-box-shadow', component: BoxShadowGeneratorComponent },
  { path: 'tools/gerador-gradiente-css', component: CssGradientGeneratorComponent },
  { path: 'tools/gerador-clip-path', component: ClipPathGeneratorComponent },
  { path: 'tools/construtor-grid-css', component: CssGridBuilderComponent },
  { path: 'tools/gerador-filtros-css', component: CssFilterGeneratorComponent },
  { path: 'tools/gerador-animacao-css', component: CssAnimationGeneratorComponent },
  { path: 'tools/gerador-cron', component: CronGeneratorComponent },
  { path: 'tools/formatador-json', component: JsonFormatterComponent },
  { path: 'tools/url-codec', component: UrlCodecComponent },
  { path: 'tools/base64-codec', component: Base64CodecComponent },
  { path: 'tools/jwt-decoder', component: JwtDecoderComponent },
  { path: 'tools/timestamp-converter', component: TimestampConverterComponent },
  { path: 'tools/n8n-expression-simulator', component: N8nExpressionSimulatorComponent },
  { path: 'tools/data-converter', component: DataConverterComponent },
  { path: 'tools/gerador-hash', component: HashGeneratorComponent },
  { path: 'tools/gerador-senha', component: PasswordGeneratorComponent },
  { path: 'tools/gerador-uuid', component: UuidGeneratorComponent },
  { path: 'tools/testador-regex', component: RegexTesterComponent },
  { path: 'tools/gerador-dados-falsos', component: MockDataGeneratorComponent },
  { path: 'tools/webhook-tester', component: WebhookTesterComponent },
  { path: 'tools/meu-ip', component: MyIpComponent },
  { path: 'tools/cliente-rest', component: RestClientComponent },
  { path: 'tools/verificador-dns', component: DnsCheckerComponent },
  { path: 'tools/verificador-ssl', component: SslCheckerComponent },
  { path: 'tools/comparador-texto', component: DiffCheckerComponent },
  { path: 'tools/docker-compose-generator', component: DockerComposeGeneratorComponent },
  { path: 'tools/gerador-qr-code', component: QrCodeGeneratorComponent },
  { path: 'tools/gerenciador-n8n', component: N8nManagerComponent },
  { path: '**', redirectTo: '', pathMatch: 'full' }
];