

import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { ToolsIndexComponent } from './components/tools/tools-index/tools-index.component';
import { CronGeneratorComponent } from './components/tools/cron-generator/cron-generator.component';
import { JsonFormatterComponent } from './components/tools/json-formatter/json-formatter.component';
import { PlaceholderComponent } from './components/shared/placeholder/placeholder.component';
import { UrlCodecComponent } from './components/tools/url-codec/url-codec.component';
import { Base64CodecComponent } from './components/tools/base64-codec/base64-codec.component';
import { JwtDecoderComponent } from './components/tools/jwt-decoder/jwt-decoder.component';
import { TimestampConverterComponent } from './components/tools/timestamp-converter/timestamp-converter.component';
import { N8nExpressionSimulatorComponent } from './components/tools/n8n-expression-simulator/n8n-expression-simulator.component';
import { DataConverterComponent } from './components/tools/data-converter/data-converter.component';
import { HashGeneratorComponent } from './components/tools/hash-generator/hash-generator.component';
import { PasswordGeneratorComponent } from './components/tools/password-generator/password-generator.component';
import { UuidGeneratorComponent } from './components/tools/uuid-generator/uuid-generator.component';
import { RegexTesterComponent } from './components/tools/regex-tester/regex-tester.component';
import { MockDataGeneratorComponent } from './components/tools/mock-data-generator/mock-data-generator.component';
import { WebhookTesterComponent } from './components/tools/webhook-tester/webhook-tester.component';
import { MyIpComponent } from './components/tools/my-ip/my-ip.component';
import { RestClientComponent } from './components/tools/rest-client/rest-client.component';
import { DnsCheckerComponent } from './components/tools/dns-checker/dns-checker.component';
import { SslCheckerComponent } from './components/tools/ssl-checker/ssl-checker.component';
import { DiffCheckerComponent } from './components/tools/diff-checker/diff-checker.component';
import { DockerComposeGeneratorComponent } from './components/tools/docker-compose-generator/docker-compose-generator.component';
import { QrCodeGeneratorComponent } from './components/tools/qr-code-generator/qr-code-generator.component';
import { BlogListComponent } from './components/blog/blog-list/blog-list.component';
import { BlogPostComponent } from './components/blog/blog-post/blog-post.component';
import { LoginComponent } from './components/login/login.component';
import { ProfileComponent } from './components/profile/profile.component';
import { N8nManagerComponent } from './components/tools/n8n-manager/n8n-manager.component';
import { ForumListComponent } from './components/forum/forum-list/forum-list.component';
import { ForumNewTopicComponent } from './components/forum/forum-new-topic/forum-new-topic.component';
import { ForumTopicComponent } from './components/forum/forum-topic/forum-topic.component';
import { TemplateListComponent } from './components/templates/template-list/template-list.component';
import { TemplateDetailComponent } from './components/templates/template-detail/template-detail.component';
import { BoxShadowGeneratorComponent } from './components/tools/box-shadow-generator/box-shadow-generator.component';
import { CssGradientGeneratorComponent } from './components/tools/css-gradient-generator/css-gradient-generator.component';
import { ClipPathGeneratorComponent } from './components/tools/clip-path-generator/clip-path-generator.component';
import { CssGridBuilderComponent } from './components/tools/css-grid-builder/css-grid-builder.component';
import { CssFilterGeneratorComponent } from './components/tools/css-filter-generator/css-filter-generator.component';
import { CssAnimationGeneratorComponent } from './components/tools/css-animation-generator/css-animation-generator.component';
import { LearningIndexComponent } from './components/learning/learning-index/learning-index.component';
import { LearningPathComponent } from './components/learning/learning-path/learning-path.component';
import { OQueEProgramacaoComponent } from './components/learning/articles/o-que-e-programacao/o-que-e-programacao.component';
import { LogicaDeProgramacaoComponent } from './components/learning/articles/logica-de-programacao/logica-de-programacao.component';
import { TiposDeDadosComponent } from './components/learning/articles/tipos-de-dados/tipos-de-dados.component';
import { IntroducaoPseudocodigoComponent } from './components/learning/articles/introducao-pseudocodigo/introducao-pseudocodigo.component';
import { ComoInternetFuncionaComponent } from './components/learning/articles/como-internet-funciona/como-internet-funciona.component';
import { HttpApisComponent } from './components/learning/articles/http-apis/http-apis.component';
import { EntendendoJsonComponent } from './components/learning/articles/entendendo-json/entendendo-json.component';
import { OQueSaoWebhooksComponent } from './components/learning/articles/o-que-sao-webhooks/o-que-sao-webhooks.component';
import { IdeConsoleComponent } from './components/learning/articles/ide-console/ide-console.component';
import { GitGithubComponent } from './components/learning/articles/git-github/git-github.component';
import { OQueEIdeComponent } from './components/learning/articles/o-que-e-ide/o-que-e-ide.component';
import { GerenciadoresPacotesNpmComponent } from './components/learning/articles/gerenciadores-pacotes-npm/gerenciadores-pacotes-npm.component';
import { IntroducaoDockerComponent } from './components/learning/articles/introducao-docker/introducao-docker.component';
import { VolumesDockerComponent } from './components/learning/articles/volumes-docker/volumes-docker.component';
import { RedesDockerComponent } from './components/learning/articles/redes-docker/redes-docker.component';
import { RegexBasicoComponent } from './components/learning/articles/regex-basico/regex-basico.component';
import { HelloWorldNodejsComponent } from './components/learning/articles/hello-world-nodejs/hello-world-nodejs.component';
import { OQueEBancoDeDadosComponent } from './components/learning/articles/o-que-e-banco-de-dados/o-que-e-banco-de-dados.component';
import { ConectandoAppBancoDadosComponent } from './components/learning/articles/conectando-app-banco-dados/conectando-app-banco-dados.component';
import { ConstruindoApiRestCrudComponent } from './components/learning/articles/construindo-api-rest-crud/construindo-api-rest-crud.component';
import { OQueEJwtComponent } from './components/learning/articles/o-que-e-jwt/o-que-e-jwt.component';
import { DockerizandoAppNodejsComponent } from './components/learning/articles/dockerizando-app-nodejs/dockerizando-app-nodejs.component';
import { OQueEVpsComponent } from './components/learning/articles/o-que-e-vps/o-que-e-vps.component';
import { PublicandoAppVpsComponent } from './components/learning/articles/publicando-app-vps/publicando-app-vps.component';
import { EntendendoExpressoesCronComponent } from './components/learning/articles/entendendo-expressoes-cron/entendendo-expressoes-cron.component';
import { OQueEN8nComponent } from './components/learning/articles/o-que-e-n8n/o-que-e-n8n.component';
import { ConhecendoInterfaceN8nComponent } from './components/learning/articles/conhecendo-interface-n8n/conhecendo-interface-n8n.component';
import { OQueENoN8nComponent } from './components/learning/articles/o-que-e-no-n8n/o-que-e-no-n8n.component';
import { PrimeiroWorkflowN8nComponent } from './components/learning/articles/primeiro-workflow-n8n/primeiro-workflow-n8n.component';

export const APP_ROUTES: Routes = [
  { path: 'login', component: LoginComponent },
  { path: 'profile', component: ProfileComponent },
  { path: '', component: HomeComponent },
  { path: 'blog', component: BlogListComponent },
  { path: 'blog/:slug', component: BlogPostComponent },
  { path: 'forum', component: ForumListComponent },
  { path: 'forum/new', component: ForumNewTopicComponent },
  { path: 'forum/:topicId', component: ForumTopicComponent },
  { path: 'templates', component: TemplateListComponent },
  { path: 'templates/:id', component: TemplateDetailComponent },
  { path: 'learning', component: LearningIndexComponent },
  { path: 'learning/:slug', component: LearningPathComponent },
  
  // Jornada do Desenvolvedor
  { path: 'learning/article/o-que-e-programacao', component: OQueEProgramacaoComponent },
  { path: 'learning/article/logica-de-programacao', component: LogicaDeProgramacaoComponent },
  { path: 'learning/article/tipos-de-dados', component: TiposDeDadosComponent },
  { path: 'learning/article/introducao-pseudocodigo', component: IntroducaoPseudocodigoComponent },
  { path: 'learning/article/como-internet-funciona', component: ComoInternetFuncionaComponent },
  { path: 'learning/article/http-apis', component: HttpApisComponent },
  { path: 'learning/article/entendendo-json', component: EntendendoJsonComponent },
  { path: 'learning/article/o-que-sao-webhooks', component: OQueSaoWebhooksComponent },
  { path: 'learning/article/ide-console', component: IdeConsoleComponent },
  { path: 'learning/article/git-github', component: GitGithubComponent },
  { path: 'learning/article/o-que-e-ide', component: OQueEIdeComponent },
  { path: 'learning/article/gerenciadores-pacotes-npm', component: GerenciadoresPacotesNpmComponent },
  { path: 'learning/article/introducao-docker', component: IntroducaoDockerComponent },
  { path: 'learning/article/volumes-docker', component: VolumesDockerComponent },
  { path: 'learning/article/redes-docker', component: RedesDockerComponent },
  { path: 'learning/article/regex-basico', component: RegexBasicoComponent },
  { path: 'learning/article/hello-world-nodejs', component: HelloWorldNodejsComponent },
  { path: 'learning/article/o-que-e-banco-de-dados', component: OQueEBancoDeDadosComponent },
  { path: 'learning/article/conectando-app-banco-dados', component: ConectandoAppBancoDadosComponent },
  { path: 'learning/article/construindo-primeira-api-rest', component: ConstruindoApiRestCrudComponent },
  { path: 'learning/article/o-que-e-jwt', component: OQueEJwtComponent },
  { path: 'learning/article/dockerizando-app-nodejs', component: DockerizandoAppNodejsComponent },
  { path: 'learning/article/o-que-e-vps', component: OQueEVpsComponent },
  { path: 'learning/article/publicando-app-vps', component: PublicandoAppVpsComponent },

  // Fundamentos n8n
  { path: 'learning/article/entendendo-expressoes-cron', component: EntendendoExpressoesCronComponent },
  { path: 'learning/article/o-que-e-n8n', component: OQueEN8nComponent },
  { path: 'learning/article/conhecendo-interface-n8n', component: ConhecendoInterfaceN8nComponent },
  { path: 'learning/article/o-que-e-no-n8n', component: OQueENoN8nComponent },
  { path: 'learning/article/primeiro-workflow-n8n', component: PrimeiroWorkflowN8nComponent },
  
  { path: 'tools', component: ToolsIndexComponent },
  { path: 'tools/gerador-box-shadow', component: BoxShadowGeneratorComponent },
  { path: 'tools/gerador-gradiente-css', component: CssGradientGeneratorComponent },
  { path: 'tools/gerador-clip-path', component: ClipPathGeneratorComponent },
  { path: 'tools/construtor-grid-css', component: CssGridBuilderComponent },
  { path: 'tools/gerador-filtros-css', component: CssFilterGeneratorComponent },
  { path: 'tools/gerador-animacao-css', component: CssAnimationGeneratorComponent },
  { path: 'tools/gerador-cron', component: CronGeneratorComponent },
  { path: 'tools/formatador-json', component: JsonFormatterComponent },
  { path: 'tools/url-codec', component: UrlCodecComponent },
  { path: 'tools/base64-codec', component: Base64CodecComponent },
  { path: 'tools/jwt-decoder', component: JwtDecoderComponent },
  { path: 'tools/timestamp-converter', component: TimestampConverterComponent },
  { path: 'tools/n8n-expression-simulator', component: N8nExpressionSimulatorComponent },
  { path: 'tools/data-converter', component: DataConverterComponent },
  { path: 'tools/gerador-hash', component: HashGeneratorComponent },
  { path: 'tools/gerador-senha', component: PasswordGeneratorComponent },
  { path: 'tools/gerador-uuid', component: UuidGeneratorComponent },
  { path: 'tools/testador-regex', component: RegexTesterComponent },
  { path: 'tools/gerador-dados-falsos', component: MockDataGeneratorComponent },
  { path: 'tools/webhook-tester', component: WebhookTesterComponent },
  { path: 'tools/meu-ip', component: MyIpComponent },
  { path: 'tools/cliente-rest', component: RestClientComponent },
  { path: 'tools/verificador-dns', component: DnsCheckerComponent },
  { path: 'tools/verificador-ssl', component: SslCheckerComponent },
  { path: 'tools/comparador-texto', component: DiffCheckerComponent },
  { path: 'tools/docker-compose-generator', component: DockerComposeGeneratorComponent },
  { path: 'tools/gerador-qr-code', component: QrCodeGeneratorComponent },
  { path: 'tools/gerenciador-n8n', component: N8nManagerComponent },
  { path: '**', redirectTo: '', pathMatch: 'full' }
];
